export const UPDATE_FRIEND_LIST_REDUCER = 'UPDATE_FRIEND_LIST_REDUCER';
export const UPDATE_CHAT_REDUCER = 'UPDATE_CHAT_REDUCER';
export const SELECT_SINGLE_FRIEND = 'SELECT_SINGLE_FRIEND';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
